
import Navbar from "../components/Navbar";
import TopBar from "../components/TopBar";
import Footer from "../components/Footer";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";

export const metadata = {
  title: "E-Commerce Site",
  description: "Generated by create next app",
};
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-lnter",

});
export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
    >
      <body className={`${poppins.variable, inter.variable}  min-h-full flex flex-col`} cz-shortcut-listen="true">
        <TopBar />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
