import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import LayoutWrapper from "@/components/LayoutWrapper";

export const metadata = {
  title: "E-Commerce Site",
  description: "Generated by create next app",
};
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-inter",

});
export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
    >
      <body className={`${poppins.variable} ${inter.variable} min-h-full flex flex-col`} cz-shortcut-listen="true">
        <LayoutWrapper>
          {children}
        </LayoutWrapper>

        <Toaster richColors position="top-right" />
      </body>
    </html>
  );
}
